// Code generated by ent, DO NOT EDIT.

package ent

import (
	"twitter/ent/schema"
	"twitter/ent/tweet"
	"twitter/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tweetFields := schema.Tweet{}.Fields()
	_ = tweetFields
	// tweetDescText is the schema descriptor for text field.
	tweetDescText := tweetFields[0].Descriptor()
	// tweet.TextValidator is a validator for the "text" field. It is called by the builders before save.
	tweet.TextValidator = tweetDescText.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
}
